version: '4'
services:
    dynasty-svc:
        platform: linux/amd64
        image: phamvantan/dynasty-svc:2.0.0
        container_name: dynasty-svc
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-production
        ports:
            - 2002:2002
        env_file:
            - .env.production
        networks:
            - dynasty_network
        volumes:
            - ./data-volumes:/app/public/assets

networks:
    dynasty_network:
        external: true
