import {
  BannerModel,
  CartModel,
  CategoryModel,
  ComboPromotionModel,
  CustomerAddressModel,
  CustomerModel,
  EmailTemplateModel,
  StockManagementModel,
  OrderModel,
  ProductAttributeModel,
  ProductFavoriteModel,
  ProductVariantModel,
  ProductModel,
  PromotionModel,
  StaffModel,
  VoucherModel,
  StoreConfigModel,
  StoreSystemModel,
  NotificationsModel,
  IngredientModel,
} from '.';

export const dbContext = {
  BannerModel,
  CartModel,
  CategoryModel,
  ComboPromotionModel,
  CustomerAddressModel,
  CustomerModel,
  EmailTemplateModel,
  StockManagementModel,
  OrderModel,
  ProductAttributeModel,
  ProductFavoriteModel,
  ProductVariantModel,
  ProductModel,
  PromotionModel,
  StaffModel,
  VoucherModel,
  StoreConfigModel,
  StoreSystemModel,
  NotificationsModel,
  IngredientModel,
};
