export * as BannerType from './banners/@type';
export * as CartType from './carts/@type';
export * as CategoryType from './category/@type';
export * as ComboPromotionType from './comboPromotions/@type';
export * as CustomerAddressType from './customerAddress/@type';
export * as CustomerType from './customers/@type';
export * as EmailConfigType from './emailConfig/@type';
export * as EmailTemplateType from './emailTemplate/@type';
export * as MaterialType from './materials/@type';
export * as OrderType from './orders/@type';
export * as ProductAttributeType from './productAttributes/@type';
export * as ProductFavoriteType from './productFavorites/@type';
export * as ProductType from './products/@type';
export * as ProductVariantType from './productVariants/@type';
export * as PromotionType from './promotions/@type';
// export * as SMSType from './smsModel/@type';
// export * as StatisticType from './statistics/@type';

export * as UserType from './users/@type';
export * as VoucherType from './vouchers/@type';
export * as StoresType from './stores/@type';
